version: '2'
services:
  web1:
    image: lbarman/prifi-demo:latest
    volumes:
      - ./scripts:/scripts:ro
      - ./prifi:/prifi
    environment:
      - STARTUPSCRIPT=/scripts/client.sh
      - WEBSITE=www.youtube.com
      - HOME=/home/ubuntu
      - SHELL=/bin/bash
    working_dir: /root
    privileged: true
    ports:
      - 8000:80
    links:
      - relay
  relay:
    image: lbarman/prifi-demo:latest
    volumes:
      - ./scripts:/scripts:ro
      - ./prifi:/prifi
    environment:
      - STARTUPSCRIPT=/scripts/relay.sh
      - HOME=/home/ubuntu
      - SHELL=/bin/bash
    working_dir: /root
    privileged: true
    ports:
      - 9000:80